Handle the no-discord-API-token case
cardinalitypuzzles/smallboard pull request #277
Opened 2020-12-30 20:05 UTC by dan-simon

What it says. I haven't added tests or checked very hard that this doesn't break other stuff and honestly what I did seemed a bit too simple.

Just to be clear, this PR is meant to, if no discord API token is in config, just not create discord channels (but otherwise do the same things).

2020-12-30 20:27 UTC, asdfryan approved these changes

2020-12-30 20:29 UTC, rgossiaux requested changes
What's the prod_db.sql file doing there?

2020-12-30 20:30 UTC, dan-simon commented
I think it wasn't caught by .gitignore. I'll remove it.

2020-12-30 22:35 UTC, akirabaruah approved these changes
LGTM with a nit - thanks Dan!

2020-12-30 22:35 UTC, akirabaruah commented on hunts/views.py
> +            if settings.CHAT_DEFAULT_SERVICE is not None:
nit: Can we simplify this to just `if settings.CHAT_DEFAULT_SERVICE:`? It's a bit nicer to read and also catches the empty string case.

2020-12-31 03:10 UTC, rgossiaux approved these changes
Thanks!

2020-12-31 03:15 UTC, merged