Add a URL redirector for Google sheets (#342)
cardinalitypuzzles/smallboard pull request #344
Opened 2021-01-10 20:09 UTC by rawxfish

This makes /puzzles/sheets/<puzzle_pk> direct to the sheets, or the home page if puzzle or sheets does not exist. I wasn't sure how to integrated it with the react or discord bots though.

2021-01-10 20:40 UTC, asdfryan commented on puzzles/views.py
> +        messages.error(
This is also testable right?

2021-01-10 20:52 UTC, rawxfish commented on puzzles/views.py
> +        messages.error(
true...

2021-01-10 21:00 UTC, akirabaruah requested changes
Overall, LGTM - thanks for adding this, @rawxfish

2021-01-10 21:04 UTC, rawxfish commented on puzzles/urls.py
> +    path("sheets/<int:puzzle_pk>", redirect_to_sheet, name="puzzle_sheet_redirect"),
will change it to `s/<pk>`

2021-01-10 21:12 UTC, rawxfish commented on puzzles/views.py
> +            f"Please wait a few minutes. If you have been waiting for a while, please ping @devs",
I made it a DISCORD_DEVS_ROLE env var that defaults to "dev"

2021-01-10 21:45 UTC, asdfryan approved these changes

2021-01-11 01:55 UTC, akirabaruah approved these changes
awesomesauce :+1: thanks!

2021-01-11 01:57 UTC, rgossiaux approved these changes
yay!

2021-01-11 02:09 UTC, merged